export interface FindWordsPuzzle {
  grid: string[][]
  validWords: string[]
  minWords: number
}

// Word list validated against Scrabble dictionary (5+ letter words only)
// Each puzzle: 5x5 grid, words formed by connecting adjacent cells (including diagonals)
// Each cell can only be used once per word

export const findWordsPuzzles: FindWordsPuzzle[] = [
  // Round 1
  {
    grid: [
      ['S', 'T', 'A', 'R', 'E'],
      ['H', 'E', 'A', 'R', 'S'],
      ['O', 'W', 'L', 'E', 'D'],
      ['P', 'E', 'R', 'S', 'O'],
      ['S', 'T', 'E', 'P', 'S'],
    ],
    validWords: ["AERATE","AERATES","ALERT","ALERTS","AREAE","AREAL","ARLES","ARSES","AWELESS","AWLESS","DEALER","DEALERS","DEALS","DEARER","DEARS","DEATH","DEATHS","DELATE","DELATES","DELES","DELETE","DELETES","DERAT","DERATE","DERATES","DERATS","DESERT","DESERTS","DOERS","DOPER","DOPERS","DOPES","DOSER","DOSERS","DOSES","DOSSEL","DOSSER","DOSSERET","DOSSERETS","DOSSERS","DOSSES","DRATS","DRAWEE","DRAWEES","DRAWER","DRAWERS","DRAWL","DRAWLER","DRAWLERS","DRAWLS","DREAR","DREARS","DRESS","EARED","EARLESS","EARLS","ELATE","ELATES","EPODE","EPODES","EPOSES","ERRATA","ERRED","ERSES","ESTER","ESTERS","ESTREAT","ESTREATS","EWERS","HEALED","HEALER","HEALERS","HEALS","HEARD","HEARER","HEARERS","HEARS","HEARSE","HEARSED","HEARSES","HEATS","HETAERA","HEWER","HEWERS","HOERS","HOPELESS","HOPER","HOPERS","HOPES","HOWES","HOWLED","HOWLER","HOWLERS","HOWLET","HOWLETS","HOWLS","LARDER","LARDERS","LARDS","LARES","LATHE","LATHES","LATHS","LEARS","LEERED","LEERS","LEETS","OWLET","OWLETS","PEELED","PEELER","PEELERS","PEELS","PEEPS","PEERED","PEERESS","PEERLESS","PEERS","PELES","PEREA","PERES","PERPS","PERSE","PERSES","PESOS","PESTER","PESTERED","PESTERER","PESTERERS","PESTERS","PETER","PETERED","PETERS","PETREL","PETRELS","POETESS","POETS","POSED","POSER","POSERS","POSES","POSSE","POSSES","POSSET","POSSETS","POWER","POWERED","POWERLESS","POWERS","PREES","PRELATE","PRELATES","PRELAW","PREOP","PREOPS","PREPS","PRESE","PRESET","PRESETS","PRESS","PREST","PREWAR","RALES","RARED","RARER","RARES","RATAL","RATALS","RATEL","RATELS","RATES","RATHE","RAWER","RAWEST","REALER","REALES","REALEST","REALS","REARER","REARERS","REARS","REATA","REDOS","REDRAW","REELED","REELER","REELERS","REELS","REEST","RELATE","RELATES","RELET","RELETS","REPOS","REPOSE","REPOSED","REPOSER","REPOSERS","REPOSES","REREDOS","RESEAL","RESEALS","RESEAT","RESEATS","RESEE","RESEES","RESET","RESETS","RESLATE","RESLATES","RESOD","RESODS","REWARD","REWARDS","REWEAR","REWEARS","REWET","REWETS","SEALED","SEALER","SEALERS","SEALS","SEARED","SEARER","SEARS","SEATS","SEELED","SEEPS","SEERESS","SEERS","SERAL","SERED","SERER","SERES","SEREST","SERRATE","SERRATES","SETAE","SETAL","SEWAR","SEWARS","SEWER","SEWERED","SEWERLESS","SEWERS","SHEAL","SHEALS","SHEAR","SHEARED","SHEARER","SHEARERS","SHEARS","SHEWER","SHEWERS","SHOELESS","SHOER","SHOERS","SHOES","SHOPS","SHOWER","SHOWERED","SHOWERER","SHOWERERS","SHOWERLESS","SHOWERS","SLATE","SLATES","SLATS","SLEDS","SLEEP","SLEEPS","SLEET","SLEETS","SLEPT","SPEEL","SPEELED","SPEELS","SPEER","SPEERED","SPEERS","SPODE","SPODES","SPREE","SPREES","STALE","STALED","STALER","STALES","STALEST","STARE","STARED","STARER","STARERS","STARES","STARLESS","STARLET","STARLETS","STARRED","STARS","STEAL","STEALER","STEALERS","STEALS","STEEL","STEELED","STEELS","STEEP","STEEPS","STEER","STEERED","STEERER","STEERERS","STEERS","STELA","STELAE","STELAR","STELE","STELES","STEPS","STERE","STEREO","STEREOS","STERES","STERLET","STERLETS","STEWARD","STEWARDESS","STEWARDS","STREEL","STREELED","STREELS","STREP","STREPS","STRESS","STREW","TAELS","TALER","TALERS","TALES","TARDO","TARED","TARES","TARRE","TARRED","TARRES","TAWER","TAWERS","TEALS","TEARED","TEARER","TEARERS","TEARLESS","TEARS","TEELS","TELAE","TELES","TELESHOP","TELESHOPS","TEREDO","TEREDOS","TERSE","TERSER","TESLA","THEWLESS","THOWLESS","TREAT","TREATS","TREELESS","TREES","TRESS","WALED","WALER","WALERS","WALES","WARDER","WARDERS","WARDS","WARED","WARES","WARLESS","WARRED","WEALS","WEARER","WEARERS","WEARS","WEEPS","WEETS","WESTER","WESTERED","WESTERS","WHEAL","WHEALS","WHEAT","WHEATS","WHETS","WHOPS","WREATH","WREATHE","WREATHES","WREATHS","WREST"],
    minWords: 15,
  },
  // Round 2
  {
    grid: [
      ['L', 'I', 'G', 'H', 'T'],
      ['O', 'N', 'E', 'S', 'A'],
      ['V', 'E', 'R', 'S', 'T'],
      ['E', 'D', 'G', 'E', 'S'],
      ['S', 'P', 'O', 'T', 'S'],
    ],
    validWords: ["ASHEN","ASHES","ASSES","ASSESS","ASSET","ASSETS","ASTER","ASTERN","ASTERS","DEEPS","DEERS","DENES","DENIER","DENIERS","DENIES","DEPOT","DEPOTS","DESPOT","DESPOTS","DEVON","DOERS","DOEST","DOGES","DOPES","DOTER","DOTERS","DOTES","DREEING","DREES","DREGS","DREIGH","DRESS","DRESSES","DREST","EDGER","EDGERS","EDGES","EGERS","EGEST","EGESTA","EGESTS","EGRESS","EGRESSES","EGRET","EGRETS","EIGHT","EIGHTS","ENVOI","EPODE","ERGOT","ERGOTS","ERNES","ERSES","ESSES","ESTATE","ESTATES","ESTER","ESTERS","ESTOP","ESTOPS","EVENER","EVENERS","EVENEST","GEEING","GEESE","GEEST","GEESTS","GENES","GENESES","GENIE","GENIES","GENRE","GENRES","GEODE","GEODES","GESTATE","GESTATES","GESTE","GESTES","GESTS","GETAS","GHAST","GHATS","GOERS","GREED","GREEDS","GREEING","GREEN","GREENLIGHT","GREENLIGHTS","GREES","HASTE","HASTES","HATER","HATERS","HATES","HEEDS","HERDS","HEREDES","HEREON","HERES","HERETO","HESTS","INGEST","INGESTA","INGESTS","INVERSE","INVERSES","LIERNE","LIERS","LIGER","LIGERS","LIGHT","LIGHTS","LINED","LINER","LINERS","LINES","LINGER","LINGERED","LINGERS","LINGS","LIONESS","LIONESSES","LONER","LONERS","LONGE","LONGER","LONGERS","LONGES","LONGEST","LONGIES","LONGS","LOVED","LOVER","LOVERS","LOVES","NEEDS","NEEPS","NEIGH","NEIGHS","NERDS","NESSES","NESTER","NESTERS","NESTS","NEVES","NIGHER","NIGHEST","NIGHS","NIGHT","NIGHTS","ODEON","OGEES","OGRES","OGRESS","OGRESSES","OVERDO","OVERDOES","OVERDOG","OVERDOGS","OVERNIGHT","OVERNIGHTS","OVERS","OVERSET","OVERSETS","OVERSTATE","OVERSTATES","PEDOGENESES","PEERESS","PEERESSES","PEERS","POETS","REDES","REDOES","REEDS","REEST","REESTS","REEVE","REEVED","REEVES","REGES","REGION","REIGN","REIGNED","REINED","RENEGE","RENEGES","RENEST","RENESTS","RENIG","RENIGS","RENVOI","REOIL","RESAT","RESEE","RESEED","RESEEDS","RESEEN","RESET","RESETS","RESTATE","RESTATES","RESTS","SASSES","SATES","SEDER","SEDERS","SEDGE","SEDGES","SEEDS","SEERESS","SEERESSES","SEERS","SEGNI","SEGNO","SEINE","SEINED","SEINER","SEINERS","SENGI","SERED","SEREIN","SERENE","SERENES","SERENEST","SERES","SEREST","SERGE","SERGED","SERGES","SESTET","SESTETS","SEVEN","SEVER","SEVERE","SEVEREST","SEVERS","SHEEN","SHEER","SHEEREST","SHEERS","SHEEVE","SHEEVES","SHERD","SHERDS","SPEED","SPEEDO","SPEER","SPEERS","SPODE","SPOTS","STASES","STASH","STASHES","STATE","STATER","STATERS","STATES","STATS","STERE","STEREO","STEREOING","STERES","STERN","STERNEST","STETS","STODGE","STODGES","STOPE","STOPED","STOPES","STOPS","TASSE","TASSES","TASSET","TASSETS","TASTE","TASTER","TASTERS","TASTES","TATER","TATERS","TATES","TEREDO","TERNE","TERNES","TERSE","TERSEST","TESTA","TESTS","THEGN","THEIN","THEINE","THERE","THEREON","THERES","THERETO","THESE","THESES","TOPED","TOPEE","TOPES","TSETSE","TSETSES","VEEPS","VEERS","VEGES","VENGE","VENGES","VERGE","VERGES","VERSE","VERSES","VERSET","VERSETS","VERST","VERSTE","VERSTES","VERSTS","VOLING"],
    minWords: 15,
  },
  // Round 3
  {
    grid: [
      ['P', 'L', 'A', 'Y', 'S'],
      ['H', 'O', 'N', 'E', 'T'],
      ['O', 'T', 'E', 'S', 'A'],
      ['N', 'E', 'S', 'T', 'R'],
      ['E', 'S', 'S', 'A', 'Y'],
    ],
    validWords: ["ALOES","ALONE","ANEAR","ANEARS","ANETHOL","ANSAE","ANSATE","ANTES","ARSENAL","ARSENO","ARSES","ASSAY","ASSENT","ASSENTS","ASSES","ASSESS","ASSESSES","ASSET","ASSETS","ASTONY","ASTRAY","EASES","EASTS","EATEN","ESNES","ESSAY","ESSES","ESTATE","ESTATES","ESTOP","ESTRAY","HONES","HONEST","HONESTEST","HONESTY","HONEY","HONEYS","HOOPLA","HOOTS","HOTNESS","HOTNESSES","LANES","LOANS","LOESS","LOESSES","LOONS","LOOTS","NEARS","NEATEST","NEATS","NEOTENY","NESSES","NESTS","NETOP","NOONS","NOTES","ONLAY","ONLAYS","ONSET","ONSETS","PHONAL","PHONE","PHONES","PHONEY","PHONEYS","PHONS","PHONY","PHOTO","PHOTON","PHOTONS","PHOTS","PLANE","PLANES","PLANET","PLANETARY","PLANETS","PLANS","PLANT","PLANTS","PLAYS","PLOTS","POETESS","POETESSES","POETRY","POETS","PONES","PONTES","PONTON","PONTONS","POONS","POTEEN","POTEENS","RASES","RATES","SARSEN","SARSENET","SARSENETS","SARSNET","SARSNETS","SASSES","SATAY","SATEEN","SATEENS","SATES","SATYR","SATYRS","SEARS","SEATS","SENSA","SENSATE","SENSATES","SENSE","SENSES","SENTE","SESTET","SESTETS","SETAE","SETON","SETONS","SNOOL","SNOOP","SNOOT","SNOOTS","SNOTS","SNYES","STARS","START","STARTS","STASES","STATE","STATES","STATS","STEAL","STEARATE","STEARATES","STENO","STENT","STENTS","STETS","STOAE","STONE","STONES","STONEY","STONY","STOOL","STOOP","STRASS","STRASSES","STRAY","STYES","SYNTH","TARTEST","TARTS","TARTY","TASSE","TASSES","TASSET","TASSETS","TASTE","TASTES","TASTY","TATAR","TATARS","TATES","TEARS","TEARY","TEASE","TEASES","TEATS","TEENS","TEENY","TEETH","TENET","TENETS","TENSE","TENSES","TENSEST","TENTH","TENTS","TESTA","TESTAE","TESTATE","TESTATES","TESTEE","TESTEES","TESTES","TESTON","TESTONS","TESTOON","TESTOONS","TESTS","TESTY","TETRA","TETRAS","TOLAN","TOLANE","TOLANES","TOLANS","TONAL","TONES","TONEY","TOONS","TRASS","TRASSES","TSARS","TSETSE","TSETSES","TYEES","TYNES","YEANS","YEARS","YEAST","YEASTS","YEASTY","YENTE","YENTES","YESES","YESSES"],
    minWords: 15,
  },
]

// Check if a word can be formed in the grid (for validation)
export function canFormWord(grid: string[][], word: string): boolean {
  const rows = grid.length
  const cols = grid[0].length

  function dfs(row: number, col: number, index: number, visited: Set<string>): boolean {
    if (index === word.length) return true
    if (row < 0 || row >= rows || col < 0 || col >= cols) return false

    const key = `${row},${col}`
    if (visited.has(key)) return false
    if (grid[row][col] !== word[index]) return false

    visited.add(key)

    const directions = [
      [-1, -1], [-1, 0], [-1, 1],
      [0, -1],           [0, 1],
      [1, -1],  [1, 0],  [1, 1],
    ]

    for (const [dr, dc] of directions) {
      if (dfs(row + dr, col + dc, index + 1, new Set(visited))) {
        return true
      }
    }

    return false
  }

  for (let row = 0; row < rows; row++) {
    for (let col = 0; col < cols; col++) {
      if (dfs(row, col, 0, new Set())) {
        return true
      }
    }
  }

  return false
}
